// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` doesn't need a connectable DB — it only reads the schema.
    // Using env() here throws when DATABASE_URL is unset, which happens whenever
    // another workspace's `bun install` runs this package's postinstall script
    // (e.g. the frontend's Railway build, which has no DATABASE_URL of its own).
    // The actual runtime connection in db.ts reads process.env.DATABASE_URL directly
    // and is unaffected by this fallback.
    url: process.env.DATABASE_URL ?? "",
  },
});
